- name: include secret vars
  include_vars:
    file: "{{ inventory_dir }}/files/secrets.yml"
    name: secrets


- name: set facts
  set_fact:
    website_bucket_endpoint: "{{ website_bucket_endpoint | default('https://s3.' + aws_region + '.amazonaws.com') }}"
    website_dist_path: "{{ playbook_dir }}/../{{ website_dist_dir }}/"


- name: Upload assets to S3 bucket (non-HTML)
  ansible.builtin.command:
    argv:
      - s5cmd
      - --numworkers=256
      - --endpoint-url={{ website_bucket_endpoint | default('https://s3.' + aws_region + '.amazonaws.com') }}
      - cp
      - --cache-control=public, max-age=31536000
      - --exclude=*.html
      - --exclude=*.xml
      - "{{ website_dist_path }}/*"
      - "s3://{{ website_bucket }}/docs/"
  environment:
    AWS_ACCESS_KEY_ID: "{{ secrets.aws_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ secrets.aws_access_secret }}"
    AWS_REGION: "{{ aws_region }}"
  changed_when: true


- name: Upload roadmaps to S3 bucket
  ansible.builtin.command:
    argv:
      - s5cmd
      - --numworkers=256
      - --endpoint-url={{ website_bucket_endpoint | default('https://s3.' + aws_region + '.amazonaws.com') }}
      - cp
      - --cache-control=public, max-age=600
      - --content-type=application/xml; charset=UTF-8
      - --include=*.xml
      - "{{ website_dist_path }}/*"
      - "s3://{{ website_bucket }}/docs/"
  environment:
    AWS_ACCESS_KEY_ID: "{{ secrets.aws_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ secrets.aws_access_secret }}"
    AWS_REGION: "{{ aws_region }}"
  changed_when: true



- name: Upload HTML to S3 bucket
  ansible.builtin.command:
    argv:
      - s5cmd
      - --numworkers=256
      - --endpoint-url={{ website_bucket_endpoint | default('https://s3.' + aws_region + '.amazonaws.com') }}
      - cp
      - --cache-control=public, max-age=600
      - --content-type=text/html; charset=UTF-8
      - --include=*.html
      - "{{ website_dist_path }}/*"
      - "s3://{{ website_bucket }}/docs/"
  environment:
    AWS_ACCESS_KEY_ID: "{{ secrets.aws_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ secrets.aws_access_secret }}"
    AWS_REGION: "{{ aws_region }}"
  changed_when: true
